label day3s4:
    "I want to sleep, but finishing this plushie for Maria is more important."
    "I glance at my bed."
    "The temptation is strong, but I manage to hang on by the skin of my teeth and pick up the half-made plushie."
    "It looks pathetic now, but it’s coming along."
    "Just a little bit more sewing to do. Then I stuff it."
    "Luckily I’ve got everything I need from my leftover materials."
    "I’ll make sure Maria loves it."
    # Sewing machine noises
    play voice "3-4-1.mp3" #potato
    pro "There... we... go!"
    "I hold up the hollow plushie."
    "It still looks a little sad, but at least it doesn’t look like someone butchered it."
    "I start to grab handfuls of stuffing and jam them it into every corner."
    "It’s kind of fun in a weird way. It’s the only part of this where I don’t need to be gentle."
    "I’ve felt like punching something all day, so this is just what I needed."
    "Once the stuffing is done, I finish the last of the stitching by hand."
    "I glance at the clock."
    "It’s nearly midnight by the time I’m done."
    "Seriously?"
    "I sigh. I still need to do some concepts for the costumes in Lauren’s play."
    "Screw getting up early to do them. I’ll just get them done now and then I’ll go to sleep."
    "I yawn."
    "The house is pretty much silent right now. It’s a refreshing change of pace, actually."
    "God, I’m tired."
    "I shake my head and slap my cheeks."
    play voice "3-4-2.mp3" #potato
    pro "Just get this done."
    "Nodding to myself, I start sketching out some ideas to show to Lauren."
    "I try to think back to the stuff we looked at today."
    "There’s the Elvis rip-off outfit for Birdie. That isn’t too hard. You can get those out of any cheap costume store."
    "It’ll be the girls that are the trickiest. They need their outfits the most. I guess I’ll just concentrate on those. The guys can take care of themselves."
    "Mostly circle skirts and blouses… That or dresses, either circle or sheath."
    "Circle is good. That’s a pretty simple thing to make. Lucky me!"
    "I remember you need petticoats to make the circle thing puff out properly, but to hell with that."
    "Way too much work and most of the girls would hate it."
    "At least, that’s what my research said. They’re supposed to itch like crazy."
    "It’s just a school play, right? I don’t need to go all out."
    "I sketch a few designs based on what I saw in books and online."
    "They’re pretty rough, but they give a good idea at what I’m aiming for."
    "Yawning, I check the clock and see it’s almost one."
    "Screw it. I’m done."
    "Getting up from my desk, I can’t even be bothered getting changed for the night."
    "I flop onto my bed."
    "My head barely touches the pillow before I’m asleep."
    jump dream4
